 

// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `Test2`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=.;Initial Catalog=Test2;User ID=sa;password=**zapped**;`
//     Schema:                 ``
//     Include Views:          `False`

//     Factory Name:          `SqlClientFactory`
// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace Test2
{
	[Alias("BusinessInfoTable")]
    public partial class BusinessInfoTable 
    {
        public string BuniessCode1 { get; set; }
        public string BuniessCode2 { get; set; }
        public string BuniessCode3 { get; set; }
        public string BuniessCode4 { get; set; }
        public byte? BuniessStatus1 { get; set; }
        public byte? BuniessStatus2 { get; set; }
        public DateTime? BuniessDateTime1 { get; set; }
        public DateTime? BuniessDateTime2 { get; set; }
        public string OtherColumn1 { get; set; }
        public string OtherColumn2 { get; set; }
        public string OtherColumn3 { get; set; }
    }

	[Alias("DBCCResult")]
    public partial class DBCCResult 
    {
        public string PageFID { get; set; }
        public string PagePID { get; set; }
        public string IAMFID { get; set; }
        public string IAMPID { get; set; }
        public string ObjectID { get; set; }
        public string IndexID { get; set; }
        public string PartitionNumber { get; set; }
        public string PartitionID { get; set; }
        public string iam_chain_type { get; set; }
        public string PageType { get; set; }
        public string IndexLevel { get; set; }
        public string NextPageFID { get; set; }
        public string NextPagePID { get; set; }
        public string PrevPageFID { get; set; }
        public string PrevPagePID { get; set; }
    }

	[Alias("DbfCheck")]
    public partial class DbfCheck 
    {
        public string FDATE { get; set; }
        public string FCHECK { get; set; }
        public string FCHECKUID { get; set; }
        public string FPREFIX { get; set; }
        public string FSRCOUTLET { get; set; }
        public string FOUTLET { get; set; }
        public string FEMPID { get; set; }
        public string FSTATID { get; set; }
        public string FTABLE { get; set; }
        public string FTABLEEXT { get; set; }
        public double? FCOVER { get; set; }
        public string FTIMEOPEN { get; set; }
        public string FTIMECLOSE { get; set; }
        public double? FSUBGRPCNT { get; set; }
        public string FCASHID { get; set; }
        public string FCASHSTAT { get; set; }
        public string FCASHREG { get; set; }
        public string FCASHSHIFT { get; set; }
        public string FPAYCNT { get; set; }
        public string FPAYEMPID { get; set; }
        public double? FITMTOT { get; set; }
        public double? FTAX1 { get; set; }
        public double? FTAX2 { get; set; }
        public double? FTAX3 { get; set; }
        public double? FTAX4 { get; set; }
        public double? FTAX5 { get; set; }
        public double? FCHECKTAX1 { get; set; }
        public double? FCHECKTAX2 { get; set; }
        public double? FCHECKTAX3 { get; set; }
        public double? FCHECKTAX4 { get; set; }
        public double? FCHECKTAX5 { get; set; }
        public double? FSC1 { get; set; }
        public double? FSC2 { get; set; }
        public double? FSC3 { get; set; }
        public double? FDISCPRE { get; set; }
        public double? FDISCPOST { get; set; }
        public double? FRNDAMT { get; set; }
        public double? FCKTOT { get; set; }
        public double? FMAXTOT { get; set; }
        public string FITMRND { get; set; }
        public string FTAXRND { get; set; }
        public string FSCRND { get; set; }
        public string FDISCRND { get; set; }
        public string FCKRND { get; set; }
        public double? FITMDEC { get; set; }
        public double? FTAXDEC { get; set; }
        public double? FSCDEC { get; set; }
        public double? FDISCDEC { get; set; }
        public double? FCKDEC { get; set; }
        public string FONTAXSC { get; set; }
        public string FLCKSTATID { get; set; }
        public string FLCKEMPID { get; set; }
        public string FPAID { get; set; }
        public string FTAKEOUT { get; set; }
        public double? FPRTCNT { get; set; }
        public double? FPRTPAGE { get; set; }
        public string FTIMELAST { get; set; }
        public string FSTATLAST { get; set; }
        public string FMODE { get; set; }
        public string FDELIEMPID { get; set; }
        public string FMEMBER { get; set; }
        public string FREFNO { get; set; }
        public string FREMARKS { get; set; }
        public string FREFPREFIX { get; set; }
        public string FREFCHECK { get; set; }
        public string FTOCHECK { get; set; }
        public string FVOID { get; set; }
        public string FVOIDCODE { get; set; }
        public string FVOIDTIME { get; set; }
        public string FVOIDEMPID { get; set; }
        public string FSECUSIGN { get; set; }
        public string FNONSALES { get; set; }
        public string FTMASSIGN { get; set; }
    }

	[Alias("DbfDatabase")]
    public partial class DbfDatabase 
    {
        public string FDATE { get; set; }
        public string FCHECK { get; set; }
        public string FCHECKUID { get; set; }
        public string FPREFIX { get; set; }
        public string FSRCOUTLET { get; set; }
        public string FOUTLET { get; set; }
        public string FEMPID { get; set; }
        public string FSTATID { get; set; }
        public string FTABLE { get; set; }
        public string FTABLEEXT { get; set; }
        public double? FCOVER { get; set; }
        public string FTIMEOPEN { get; set; }
        public string FTIMECLOSE { get; set; }
        public double? FSUBGRPCNT { get; set; }
        public string FCASHID { get; set; }
        public string FCASHSTAT { get; set; }
        public string FCASHREG { get; set; }
        public string FCASHSHIFT { get; set; }
        public string FPAYCNT { get; set; }
        public string FPAYEMPID { get; set; }
        public double? FITMTOT { get; set; }
        public double? FTAX1 { get; set; }
        public double? FTAX2 { get; set; }
        public double? FTAX3 { get; set; }
        public double? FTAX4 { get; set; }
        public double? FTAX5 { get; set; }
        public double? FCHECKTAX1 { get; set; }
        public double? FCHECKTAX2 { get; set; }
        public double? FCHECKTAX3 { get; set; }
        public double? FCHECKTAX4 { get; set; }
        public double? FCHECKTAX5 { get; set; }
        public double? FSC1 { get; set; }
        public double? FSC2 { get; set; }
        public double? FSC3 { get; set; }
        public double? FDISCPRE { get; set; }
        public double? FDISCPOST { get; set; }
        public double? FRNDAMT { get; set; }
        public double? FCKTOT { get; set; }
        public double? FMAXTOT { get; set; }
        public string FITMRND { get; set; }
        public string FTAXRND { get; set; }
        public string FSCRND { get; set; }
        public string FDISCRND { get; set; }
        public string FCKRND { get; set; }
        public double? FITMDEC { get; set; }
        public double? FTAXDEC { get; set; }
        public double? FSCDEC { get; set; }
        public double? FDISCDEC { get; set; }
        public double? FCKDEC { get; set; }
        public string FONTAXSC { get; set; }
        public string FLCKSTATID { get; set; }
        public string FLCKEMPID { get; set; }
        public string FPAID { get; set; }
        public string FTAKEOUT { get; set; }
        public double? FPRTCNT { get; set; }
        public double? FPRTPAGE { get; set; }
        public string FTIMELAST { get; set; }
        public string FSTATLAST { get; set; }
        public string FMODE { get; set; }
        public string FDELIEMPID { get; set; }
        public string FMEMBER { get; set; }
        public string FREFNO { get; set; }
        public string FREMARKS { get; set; }
        public string FREFPREFIX { get; set; }
        public string FREFCHECK { get; set; }
        public string FTOCHECK { get; set; }
        public string FVOID { get; set; }
        public string FVOIDCODE { get; set; }
        public string FVOIDTIME { get; set; }
        public string FVOIDEMPID { get; set; }
        public string FSECUSIGN { get; set; }
        public string FNONSALES { get; set; }
        public string FTMASSIGN { get; set; }
    }

	[Alias("Demo")]
    public partial class Demo : IHasId<string> 
    {
        [Alias("Guid")]
        [Required]
        public string Id { get; set; }
        public DateTime? Date1 { get; set; }
        public DateTime? Date2 { get; set; }
        public DateTime? Date3 { get; set; }
    }

	[Alias("Demo2")]
    public partial class Demo2 : IHasId<int> 
    {
        [Alias("RowId")]
        [AutoIncrement]
        public int Id { get; set; }
        [Required]
        public string Rand1 { get; set; }
        [Required]
        public string Rand2 { get; set; }
    }

	[Alias("Department")]
    public partial class Department 
    {
        [AutoIncrement]
        public int DepartmentID { get; set; }
        [Required]
        public string GroupName { get; set; }
        public string Company { get; set; }
    }

	[Alias("Employees")]
    public partial class Employee : IHasId<int> 
    {
        [Alias("EmployeeID")]
        [AutoIncrement]
        public int Id { get; set; }
        [Required]
        public string LastName { get; set; }
        [Required]
        public string FirstName { get; set; }
        public string Title { get; set; }
        public string TitleOfCourtesy { get; set; }
        public DateTime? BirthDate { get; set; }
        public DateTime? HireDate { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string HomePhone { get; set; }
        public string Extension { get; set; }
        public byte[] Photo { get; set; }
        public string Notes { get; set; }
        public int? ReportsTo { get; set; }
        public string PhotoPath { get; set; }
    }

	[Alias("Mar_Card")]
    public partial class Mar_Card : IHasId<int> 
    {
        [Alias("RowId")]
        [AutoIncrement]
        public int Id { get; set; }
        [Required]
        public int CustId { get; set; }
        [Required]
        public string CardId { get; set; }
        [Required]
        public string LogoUrl { get; set; }
        [Required]
        public string CardType { get; set; }
        [Required]
        public string CodeType { get; set; }
        [Required]
        public string Title { get; set; }
        public string SubTitle { get; set; }
        [Required]
        public string Color { get; set; }
        [Required]
        public string Notice { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        public int Quantity { get; set; }
        [Required]
        public string DateType { get; set; }
        public DateTime? DateBeginTime { get; set; }
        public DateTime? DateEndTime { get; set; }
        public int? DateFixedTerm { get; set; }
        public int? DateFixedBeginTerm { get; set; }
        public bool? BindOpenid { get; set; }
        public string ServicePhone { get; set; }
        public int? GetLimit { get; set; }
        public int? UseLimit { get; set; }
        public bool? CanShare { get; set; }
        public bool? CanGiveFriend { get; set; }
        public string AcceptCategory { get; set; }
        public string RejectCategory { get; set; }
        public string AcceptProduct { get; set; }
        public string RejecProduct { get; set; }
        [Required]
        public decimal ReduceCost { get; set; }
        [Required]
        public decimal LeastCost { get; set; }
        [Required]
        public decimal Discount { get; set; }
        public bool? CanUseWithOtheDiscount { get; set; }
        public string BusinessService { get; set; }
        public string TimeLimit { get; set; }
        [Required]
        public string AbstractIntro { get; set; }
        [Required]
        public string AbstractIconUrlList { get; set; }
        public byte? ConsumeType { get; set; }
        public bool? ConsumeNeedVerifyCode { get; set; }
        public string ConsumeVerifyCode { get; set; }
        public bool? ConsumeNeedRemarkAmount { get; set; }
        public string BranchNo { get; set; }
        [Required]
        public byte Status { get; set; }
        [Required]
        public int SendNum { get; set; }
        [Required]
        public int UseNum { get; set; }
        [Required]
        public int QuantityThreshold { get; set; }
        [Required]
        public int QuantityThresholdNotificCount { get; set; }
        [Required]
        public byte QuantityThresholdNotificStatus { get; set; }
        [Required]
        public DateTime CreateTime { get; set; }
        [Required]
        public int CreateUser { get; set; }
        [Required]
        public DateTime UpdateTime { get; set; }
        [Required]
        public int UpdateUser { get; set; }
        [Required]
        public bool DeleteFlag { get; set; }
        [Required]
        public int DeleteUser { get; set; }
        [Required]
        public DateTime DeleteTime { get; set; }
    }

	[Alias("Mar_CardTicket")]
    public partial class Mar_CardTicket : IHasId<int> 
    {
        [Alias("RowId")]
        [AutoIncrement]
        public int Id { get; set; }
        [Required]
        public string CardNo { get; set; }
        [Required]
        public string CardId { get; set; }
        [Required]
        public int CustId { get; set; }
        [Required]
        public byte Status { get; set; }
        public string OpenId { get; set; }
        public DateTime? LockExpireTime { get; set; }
        public string ActivityId { get; set; }
        public byte? ActivityType { get; set; }
        public DateTime? BeginTime { get; set; }
        public DateTime? EndTime { get; set; }
        [Required]
        public DateTime CreateTime { get; set; }
        [Required]
        public string CreateUser { get; set; }
        [Required]
        public DateTime UpdateTime { get; set; }
        [Required]
        public int UpdateUser { get; set; }
    }

	[Alias("MiniProfilerClientTimings")]
    public partial class MiniProfilerClientTiming : IHasId<int> 
    {
        [Alias("RowId")]
        [AutoIncrement]
        public int Id { get; set; }
        [Required]
        public Guid Id { get; set; }
        [Required]
        public Guid MiniProfilerId { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public decimal Start { get; set; }
        [Required]
        public decimal Duration { get; set; }
    }

	[Alias("MiniProfilers")]
    public partial class MiniProfiler : IHasId<int> 
    {
        [Alias("RowId")]
        [AutoIncrement]
        public int Id { get; set; }
        [Required]
        public Guid Id { get; set; }
        public Guid? RootTimingId { get; set; }
        [Required]
        public DateTime Started { get; set; }
        [Required]
        public decimal DurationMilliseconds { get; set; }
        public string User { get; set; }
        [Required]
        public bool HasUserViewed { get; set; }
        public string MachineName { get; set; }
        public string CustomLinksJson { get; set; }
        public int? ClientTimingsRedirectCount { get; set; }
    }

	[Alias("MiniProfilerTimings")]
    public partial class MiniProfilerTiming : IHasId<int> 
    {
        [Alias("RowId")]
        [AutoIncrement]
        public int Id { get; set; }
        [Required]
        public Guid Id { get; set; }
        [Required]
        public Guid MiniProfilerId { get; set; }
        public Guid? ParentTimingId { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public decimal DurationMilliseconds { get; set; }
        [Required]
        public decimal StartMilliseconds { get; set; }
        [Required]
        public bool IsRoot { get; set; }
        [Required]
        public short Depth { get; set; }
        public string CustomTimingsJson { get; set; }
    }

	[Alias("MyTable")]
    public partial class MyTable : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set; }
        public string SomeTextField { get; set; }
    }

	[Alias("Posts")]
    public partial class Post : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set; }
        [Required]
        public string Text { get; set; }
        [Required]
        public DateTime CreationDate { get; set; }
        [Required]
        public DateTime LastChangeDate { get; set; }
        public int? Counter1 { get; set; }
        public int? Counter2 { get; set; }
        public int? Counter3 { get; set; }
        public int? Counter4 { get; set; }
        public int? Counter5 { get; set; }
        public int? Counter6 { get; set; }
        public int? Counter7 { get; set; }
        public int? Counter8 { get; set; }
        public int? Counter9 { get; set; }
    }

	[Alias("Sales")]
    public partial class Sale : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set; }
        [Required]
        public DateTime Date { get; set; }
        [Required]
        public short ItemId { get; set; }
        [Required]
        public decimal Price { get; set; }
        [Required]
        public decimal Quantity { get; set; }
    }

	[Alias("Sales2")]
    public partial class Sales2 
    {
        [AutoIncrement]
        public int Id { get; set; }
        [Required]
        public DateTime Date { get; set; }
        [Required]
        public short ItemId { get; set; }
        [Required]
        public decimal Price { get; set; }
        [Required]
        public decimal Quantity { get; set; }
    }

	[Alias("Sales3")]
    public partial class Sales3 
    {
        [AutoIncrement]
        public int Id { get; set; }
        [Required]
        public DateTime Date { get; set; }
        [Required]
        public short ItemId { get; set; }
        [Required]
        public decimal Price { get; set; }
        [Required]
        public decimal Quantity { get; set; }
    }

	[Alias("Sales4")]
    public partial class Sales4 
    {
        [AutoIncrement]
        public int Id { get; set; }
        [Required]
        public DateTime Date { get; set; }
        [Required]
        public short ItemId { get; set; }
        [Required]
        public decimal Price { get; set; }
        [Required]
        public decimal Quantity { get; set; }
    }

	[Alias("Sales5")]
    public partial class Sales5 
    {
        [AutoIncrement]
        public int Id { get; set; }
        [Required]
        public DateTime Date { get; set; }
        [Required]
        public short ItemId { get; set; }
        [Required]
        public decimal Price { get; set; }
        [Required]
        public decimal Quantity { get; set; }
    }

	[Alias("Sales6")]
    public partial class Sales6 
    {
        [AutoIncrement]
        public int Id { get; set; }
        [Required]
        public DateTime Date { get; set; }
        [Required]
        public short ItemId { get; set; }
        [Required]
        public decimal Price { get; set; }
        [Required]
        public decimal Quantity { get; set; }
    }

	[Alias("Sales7")]
    public partial class Sales7 : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set; }
        [Required]
        public DateTime Date { get; set; }
        [Required]
        public short ItemId { get; set; }
        [Required]
        public decimal Price { get; set; }
        [Required]
        public decimal Quantity { get; set; }
    }

	[Alias("wt_adm_area_test")]
    public partial class wt_adm_area_test 
    {
        [AutoIncrement]
        public int ID { get; set; }
        [Required]
        public string AreaID { get; set; }
        [Required]
        public string AreaName { get; set; }
        [Required]
        public string ParentId { get; set; }
        [Required]
        public string ShortName { get; set; }
        [Required]
        public byte LevelType { get; set; }
        public string CityCode { get; set; }
        public string ZipCode { get; set; }
        [Required]
        public string AreaNamePath { get; set; }
        [Required]
        public string AreaIDPath { get; set; }
        [Required]
        public decimal Lng { get; set; }
        [Required]
        public decimal Lat { get; set; }
        public string PinYin { get; set; }
        public string ShortPinYin { get; set; }
        public string PYFirstLetter { get; set; }
        [Required]
        public int SortOrder { get; set; }
        [Required]
        public byte Status { get; set; }
        [Required]
        public byte HotCity { get; set; }
        [Required]
        public DateTime CreateTime { get; set; }
        [Required]
        public int CreateUser { get; set; }
        [Required]
        public DateTime UpdateTime { get; set; }
        [Required]
        public int UpdateUser { get; set; }
        [Required]
        public bool DeleteFlag { get; set; }
        [Required]
        public DateTime DeleteTime { get; set; }
        [Required]
        public int DeleteUser { get; set; }
    }

}
#pragma warning restore 1591
